feat: make tests share codebase
RealShadowNova/joshdb-providers pull request #11
Opened 2022-01-09 00:44 UTC by WilsontheWolf

Makes all tests share one codebase.
Might want to fix some stuff up I just kinda @ts-ignored everything.

2022-01-09 01:27 UTC, RealShadowNova requested changes
It's a good start, please rename the `tests/base.ts` file to the name of the function being exported.

2022-01-09 01:27 UTC, RealShadowNova commented on tsconfig.eslint.json
> +		"tests/base.ts"
```suggestion
		"tests/**/*.ts
```

2022-01-09 01:27 UTC, RealShadowNova commented on tests/base.ts
> +	describe('Provider', () => {
```suggestion
	describe(Provider.prototype.constructor.name, () => {
```

2022-01-09 01:27 UTC, RealShadowNova commented on tests/base.ts
> +			test('GIVEN typeof Provider THEN returns function', () => {
```suggestion
			test(`GIVEN typeof ${Provider.prototype.constructor.name} THEN returns function`, () => {
```

2022-01-09 01:27 UTC, RealShadowNova commented on tests/base.ts
> +export default (Provider: typeof JoshProvider, ProviderError: typeof JoshProviderError, providerData: unknown) => {
```suggestion
import { JoshProvider, JoshProviderError, MathOperator, Method, Payload } from '@joshdb/core';

export default (Provider: typeof JoshProvider, ProviderError: typeof JoshProviderError, providerOptions: JoshProvider.Options) {
```

2022-01-09 01:38 UTC, RealShadowNova requested changes
Just some more changes rq

2022-01-09 01:38 UTC, RealShadowNova commented on packages/json/tests/lib/JSONProvider.test.ts
> +import tests from '../../../../tests/base';
```suggestion
import { runProviderTest } from '../../../../tests/runProviderTest';
```

2022-01-09 01:38 UTC, RealShadowNova commented on packages/json/tests/lib/JSONProvider.test.ts
> +tests(JSONProvider, JSONProviderError, { dataDirectoryName: '.tests' });
```suggestion
runProviderTests<JSONProvider.Options>(JSONProvider, JSONProviderError, { dataDirectoryName: '.tests' });
```

2022-01-09 01:38 UTC, RealShadowNova commented on packages/mongo/tests/lib/MongoProvider.test.ts
> +import tests from '../../../../tests/base';
```suggestion
import { runProviderTest } from '../../../../tests/runProviderTest';
```

2022-01-09 01:38 UTC, RealShadowNova commented on packages/mongo/tests/lib/MongoProvider.test.ts
> +tests(MongoProvider, MongoProviderError, { collectionName: 'josh-test' });
```suggestion
runProviderTest<MongoProvider.Options>(MongoProvider, MongoProviderError, { collectionName: 'josh-test' });
```

2022-01-09 01:54 UTC, WilsontheWolf commented
> please rename the `tests/base.ts` file to the name of the function being exported

Would that be `tests/tests.ts` or `tests/index.ts`

2022-01-09 01:56 UTC, RealShadowNova commented
> > please rename the `tests/base.ts` file to the name of the function being exported
> 
> Would that be `tests/tests.ts` or `tests/index.ts`

It would be like `tests/runProviderTest.ts`

2022-01-09 06:55 UTC, RealShadowNova requested changes
If it becomes necessary, which I don't believe it will be, you can add a generic for `ProviderError`. Other then that, it looks good at this time.

2022-01-09 06:55 UTC, RealShadowNova commented on tests/runProviderTest.ts
> +) {
This should hopefully fix all of those `@ts-expect-error`s.

```suggestion
export function runProviderTest<Provider extends JoshProvider, ProviderOptions extends JoshProvider.Options>(
	Provider: typeof Provider,
	ProviderError: typeof JoshProviderError,
	providerOptions: ProviderOptions
) {
```

2022-01-09 06:55 UTC, RealShadowNova commented on tests/runProviderTest.ts
> +				await provider.init({ name: 'josh-test' });
```suggestion
				await provider.init({ name: 'provider' });
```

2022-01-09 06:58 UTC, RealShadowNova requested changes

2022-01-09 06:58 UTC, RealShadowNova commented on packages/mongo/tests/lib/MongoProvider.test.ts
> +runProviderTest<MongoProvider.Options>(MongoProvider, MongoProviderError, { collectionName: 'josh-test' });
`collectionName` falls back to the name passed in `init()` so this isn't needed.

```suggestion
runProviderTest<MongoProvider.Options>(MongoProvider, MongoProviderError);
```

2022-01-09 07:35 UTC, RealShadowNova requested changes

2022-01-09 07:35 UTC, RealShadowNova commented on packages/json/tests/lib/JSONProvider.test.ts
> +runProviderTest<JSONProvider.Options>(JSONProvider, JSONProviderError, { dataDirectoryName: '.tests' });
```suggestion
runProviderTest<JSONProvider, JSONProvider.Options>(JSONProvider, JSONProviderError, { dataDirectoryName: '.tests' });
```

2022-01-09 07:35 UTC, RealShadowNova commented on packages/mongo/tests/lib/MongoProvider.test.ts
> +runProviderTest<MongoProvider.Options>(MongoProvider, MongoProviderError);
```suggestion
runProviderTest<MongoProvider, MongoProvider.Options>(MongoProvider, MongoProviderError);
```

2022-01-10 04:24 UTC, RealShadowNova approved these changes

2022-01-10 04:25 UTC, merged