feat(docs): update guide with script tool
RealShadowNova/joshdb-providers pull request #20
Opened 2022-01-24 21:14 UTC by RealShadowNova

- Add `scripts/generate.mjs` script prompter tool.
- Change `docs/` to implement new generation script tool.

2022-01-24 21:35 UTC, dan-online requested changes
Just a couple changes but overall looks good, I like the nice touch of a spinner

2022-01-24 21:35 UTC, dan-online commented on docs/ContributingYourOwnProvider.md
> +This page will help guide you through the process of creating and contributing your own provider to the Josh database wrapper project. We are glad that you would like to contribute to our amazing pro
> creating or contributing to a provider

would work better here

2022-01-24 21:35 UTC, dan-online commented on docs/ContributingYourOwnProvider.md
> +yarn
Specify that yarn is a requirement because we use workspaces

2022-01-24 21:35 UTC, dan-online commented on scripts/generate.mjs
> +if (response.name === undefined) process.exit(1);
Perhaps also log an error if this code has the possibility to occur

2022-01-24 21:35 UTC, dan-online commented on scripts/generate.mjs
> +		JSON.stringify(
I believe this generates uglified code so perhaps pass the correct arguments to pad the output

2022-01-24 21:35 UTC, dan-online commented on scripts/generate.mjs
> +		resolve(provider, 'jest.config.ts'),
Maybe move this to a file instead of this method but it's not too necessary

2022-01-24 21:43 UTC, RealShadowNova commented on scripts/generate.mjs
> +if (response.name === undefined) process.exit(1);
This only occurs when you `^C` during the prompts.

2022-01-25 05:47 UTC, dan-online approved these changes
LGTM

2022-01-25 05:47 UTC, dan-online commented on docs/ContributingYourOwnProvider.md
> +This page will help guide you through the process of creating and/or contributing a provider or your own to the Josh database wrapper project. We are glad that you would like to contribute to our ama
Repetitive "or" here

2022-01-25 06:19 UTC, dan-online approved these changes

2022-01-25 18:40 UTC, merged