feat(mongo): add overwrite to setMany, add DeleteMany method, add overwrite test
RealShadowNova/joshdb-providers pull request #24
Opened 2022-02-12 22:43 UTC by dan-online

2022-02-12 23:10 UTC, RealShadowNova requested changes

2022-02-12 23:10 UTC, RealShadowNova commented on .gitignore
> +.yarnrc
We don't use Yarn 2 or 3, so why?

2022-02-12 23:12 UTC, dan-online commented on packages/mongo/src/lib/MongoProvider.ts
> +    Reflect.set(payload, 'data', deserialized);
Sure but is there a performance benefit?

2022-02-12 23:13 UTC, dan-online commented on packages/mongo/src/lib/MongoProvider.ts
> +    payload.data = docs.length > 0 ? docs.map((doc) => this._deserialize(doc.value)) : undefined;
I felt you would prefer a more inline approach?

2022-02-13 07:01 UTC, RealShadowNova commented on packages/mongo/src/lib/MongoProvider.ts
> +    payload.data = docs.length > 0 ? docs.map((doc) => this._deserialize(doc.value)) : undefined;
```suggestion
    if (docs.length > 0) payload.data = docs.map((doc) => this._deserialize(doc.value));
```
Could easily do this, still inline. If we don't need to set a property on an object let's not.

2022-02-13 07:02 UTC, RealShadowNova commented on .gitignore
> +.yarnrc
Oh ok, did not know you do use it. Good to know, all good.

2022-02-13 07:21 UTC, RealShadowNova commented on packages/mongo/src/lib/MongoProvider.ts
> +    Reflect.set(payload, 'data', deserialized);
Maybe, but that's not my concern, just mainly just because it's being used once like that seems useless imho.

2022-02-13 08:58 UTC, RealShadowNova approved these changes

2022-02-13 08:59 UTC, merged